/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsToolsRouteImport } from './routes/docs.tools'
import { Route as DocsProvidersRouteImport } from './routes/docs.providers'
import { Route as DocsInstallRouteImport } from './routes/docs.install'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsConfigRouteImport } from './routes/docs.config'
import { Route as DocsCommandsRouteImport } from './routes/docs.commands'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsToolsRoute = DocsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProvidersRoute = DocsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigRoute = DocsConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/config': typeof DocsConfigRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/providers': typeof DocsProvidersRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/config': typeof DocsConfigRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/providers': typeof DocsProvidersRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/config': typeof DocsConfigRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/providers': typeof DocsProvidersRoute
  '/docs/tools': typeof DocsToolsRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/commands'
    | '/docs/config'
    | '/docs/faq'
    | '/docs/install'
    | '/docs/providers'
    | '/docs/tools'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/commands'
    | '/docs/config'
    | '/docs/faq'
    | '/docs/install'
    | '/docs/providers'
    | '/docs/tools'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/commands'
    | '/docs/config'
    | '/docs/faq'
    | '/docs/install'
    | '/docs/providers'
    | '/docs/tools'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tools': {
      id: '/docs/tools'
      path: '/tools'
      fullPath: '/docs/tools'
      preLoaderRoute: typeof DocsToolsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/providers': {
      id: '/docs/providers'
      path: '/providers'
      fullPath: '/docs/providers'
      preLoaderRoute: typeof DocsProvidersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/config': {
      id: '/docs/config'
      path: '/config'
      fullPath: '/docs/config'
      preLoaderRoute: typeof DocsConfigRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsConfigRoute: typeof DocsConfigRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsInstallRoute: typeof DocsInstallRoute
  DocsProvidersRoute: typeof DocsProvidersRoute
  DocsToolsRoute: typeof DocsToolsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCommandsRoute: DocsCommandsRoute,
  DocsConfigRoute: DocsConfigRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsInstallRoute: DocsInstallRoute,
  DocsProvidersRoute: DocsProvidersRoute,
  DocsToolsRoute: DocsToolsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
